### ISSUE TITLE
[Feature] Support whole-buffer workflow

### ISSUE THREAD

**Issue by jemag** [woosaaahh/sj.nvim#5]
# Description

With the current workflow, if I am in a file and I know that I want to search for the word `asdkfl`, if that word is on-screen, all is good. However, if that word happens to be slightly lower or above in the file, I will then need to cancel `sj` and do a regular `/` string search.

# Alternative workflow

If the string is not onscreen but somewhere else in the file, pressing enter will go to its first occurrence. You could also potentially press a key to go to the previous or next occurrence of the word (as in regular search).

# Implementation ideas

- Allow directional search (forward or back)
- Allow going to previous or next occurrence (to avoid repeating the search when multiple occurrences are spread far apart in the buffer)

Disclaimer: this is something that is already implemented in vim-searchx (https://github.com/hrsh7th/vim-searchx). The keybinds give an idea of how you may navigate using that workflow:
![image](https://user-images.githubusercontent.com/7985687/191116391-92b6ba4b-5eeb-4d94-8a02-4d644c63484d.png)

## Final thoughts

I really  enjoy your plugin and would like to switch to it, if only for the fact that it is written in Lua, and the use of `:` allowing lower-case labels. However, this is the only workflow that seems to be missing for me.

I realize that this might not be the simplest thing to implement or that you simply may not wish to implement it. If that is the case, please let me know. 

If you are interested but would like some help, I could try my hand at a PR, but obviously I currently have much less experience in Lua and plugin writing.

**Comment by woosaaahh** [comment]
Thanks a lot for your comment and the time you took to write this !

I agree with you that supporting searching the whole buffer and navigating previous/next occurences would help and I was thinking about this a lot recently.

Actually, I implemented a "lines scope" feature today. (not released yet)
It supports searching in the visible lines above/below and in the current line (f/F).

I'm still working on the refactor and might release it during the week,
then I'll add these two features.

Btw, I'm ok to add features because I agree we need them, 
not because a plugin already implement them ! :smile: 

Thanks again for you comment

**Comment by woosaaahh** [comment]
Just in case, as there are no release yet, this issue must be kept open.

**Comment by jemag** [comment]
@woosaaahh that actually sounds great. Really curious to try it out.  

The only thing I am wondering is if the index cache might be confusing in some situations.
For example, let's say I searched for the word `vim` and took the match and now my cursor is currently here:
![image](https://user-images.githubusercontent.com/7985687/191398551-db22d9ca-bb83-4608-ba77-45d242fbdef6.png)
Now if I browse around in the file and move my cursor upward, with regular search you would expect your next match to go to the next visual occurrence (purple arrow), but instead it will go to the next match index (red `X`):
![image](https://user-images.githubusercontent.com/7985687/191398997-a34c7dc7-5701-4102-99df-d38e07662db5.png)
If that is the behavior, I think it might be a bit confusing since you need to remember which occurrence is next and since it would be a departure from vim's default search behavior of using the next visual occurrence. 


If you ever need someone to test out a branch/PR, please let me know.

**Comment by woosaaahh** [comment]
@jemag Thanks a lot for the comment and the time you took to write it !
Your comments are simple to read and detailed, I REALLY appreciate the effort !

You're right ! It makes more sense and is more natural to jump to the next occurence after the cursor postion ! I fixed it !

Except one feature (send matches to qflist), no more features will be added until the next release.

**Comment by woosaaahh** [comment]
@jemag I just released the version 0.5.

I still have some issues with "jump to prev/next match" after the search so I skipped it for the release but you can still use it while searching.

I'll add this later for sure !

Meanwhile, could you try the 5.0 and tell me what you think, please ?

You and everyone can also discuss about the new version here : [Discussion : version 0.5](https://github.com/woosaaahh/sj.nvim/discussions/7).

We keep this issue open.

**Comment by jemag** [comment]
@woosaaahh getting `module sj not found`. Seems you moved from sj file to multiple files, however you forgot to add the `sj` folder to contain all those files I believe.

Should be `lua/sj/*.lua` instead of `lua/*.lua`

**Comment by woosaaahh** [comment]
@jemag I just added an option to update the search register called `update_search_register` ( easy to remember :smile: ).
This option is set to `false` by default.

The advantage of this option is that when you're done searching, you can now use the native jump to prev/next match feature. It has a more general benefit, so I thought it could be good to add this option.

I hope at least it'll help you waiting until I add the feature.

I updated the code in keymaps samples on how to use it [here](https://github.com/woosaaahh/sj.nvim/blob/0.5/README.md?plain=1#L126).

**Comment by jemag** [comment]
hey @woosaaahh  thanks for all the great work. Really enjoying the `update_search_register` option.

That being said there seems to be a couple issues.
1- It seems like currently empty `vim.notify`  are being sent on startup and every time `sj.run` is triggered. I believe this is because your `utils.warn` function always send these events, even if empty.

You may not notice it on your side, but for those using plugins like https://github.com/rcarriga/nvim-notify, it becomes quite apparent:
![image](https://user-images.githubusercontent.com/7985687/192407081-673295f6-aa08-4fae-a591-e9e600f9aa0d.png)
Nevertheless, probably best not to send notifications, even if they are empty.

2- This is not really an issue, but perhaps a less convenient workflow. Currently with `  search_scope = "buffer"`, if my cursor is here at line 628:
![image](https://user-images.githubusercontent.com/7985687/192407264-c4fe6188-9570-4dc4-9c84-d11345bf2841.png)
And I want to navigate to the next `nvim`, using sj.run will instead take me back to the beginning of the file:
![image](https://user-images.githubusercontent.com/7985687/192407356-0bb4b84d-953d-4e68-acdf-4397f49f4f67.png)
This means that if I want to navigate to the `nvim` on line 630, I would essentially have to start back from the beginning and keep hitting "next match" until I come back to that point, which is probably not the most efficient workflow.

For this, being able to provide a direction (like `/` and `?`) and starting from the current line would probably be more efficient (basically following the regular search workflow). So in the scenario from line 628, using something like `sj.run({ dir = 'forward'})` would land me on the red arrow as the first choice, while `sj.run({ dir = 'backward'})` would land me on the purple arrow as the first choice. This would also prevent jumping back to the beginning of the file.
![image](https://user-images.githubusercontent.com/7985687/192407994-1749b470-a2e8-4df1-a936-32a5fb492901.png)

**Comment by woosaaahh** [comment]
Thanks for the report !

1- It's easily fixable !
2- It's actually the "normal" behavior... I call it "absolute jumps"

When I first implemented the POC for "jump to prev/next match" (after search), I realized that as you said, the code is not based on cursor position (relative jumps).

I like absolute jumps and relative jumps make sense too ! I'll add an option to choose between absolute and relative jumps.
I have already a lot of the code ready.
I'll work on it today as soon as I can !

**Comment by woosaaahh** [comment]
@jemag I just pushed two commits for relative labels (from cursor position), backward/forward search and jump to prev/next match. FINALLY !!! :smile: 

relative labels + backward/forward search : 61aaa9b6d67e0fd36c7e751d00086397ed85ac07
jump to prev/next match : e11d4d4cdeabc194e612931574d47e5a3a03b90a

NOTE : by default and to keep previous behavior, you have to 'opt-in' for relative labels. Like most options, you can set `relative_labels` either via the `sj.setup()` function or from keymaps.

I updated the readme to reflect the new features both for the options and the keymaps.

I hope it will bring you what you need for your worflow !

Thank you A LOOOOOT for your patience, your detailed comments and for your help in general !!! I really appreciate it.

If you think the new features solve this issue, please feel free to close it.

**Comment by jemag** [comment]
hey @woosaaahh, thanks for all the great work. I have been really busy the last few days, but just tested it quickly and it really does seem to match my workflow nicely so far.

The only thing I was wondering, is if with relative labels it would be better to label only within the visual field or not. For example, if I search `nvim` here, the labels will be exhausted looking forward
![image](https://user-images.githubusercontent.com/7985687/193285053-bacf5cb5-dda1-4bf4-94b9-1f3bc2cb851a.png)
I am wondering whether it would be more practical to have those labels only in the current visual fields (and therefore showing both labels above and below), since users might not use the ones outside of it (basically using labels `a` to `g` below and `h`++ above). But maybe that is starting to get too complicated lol.

Either way, really liking the workflow that relative labels and backward/forward search allows. Will try to test more exhaustively in the coming days.

**Comment by woosaaahh** [comment]
whole buffer workflow : 50e008ddaac086ad18f67ebb5d8df8869f1e4424
relative labels + forward/backward search: 61aaa9b6d67e0fd36c7e751d00086397ed85ac07
prev/next match after search : e11d4d4cdeabc194e612931574d47e5a3a03b90a
